apiVersion: skaffold/v4beta10
kind: Config
build:
  artifacts:
    - image: yonrazticketing/auth 
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonrazticketing/client 
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.jsx
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonrazticketing/items 
      context: items
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonrazticketing/orders 
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: yonrazticketing/expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: yonrazticketing/payments 
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/zookeeper-depl.yaml
    - ./infra/k8s/kafka-depl.yaml
    - ./infra/k8s/*
deploy:
  kubectl: {}

 