apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: myticketing-dev-420512
  artifacts:
    - image: yonrazticketing/auth    # us.gcr.io/myticketing-dev-420512/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: yonrazticketing/client # us.gcr.io/myticketing-dev-420512/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.tsx"
            dest: .
          - src: "src/**/*.jsx"
            dest: .
    - image: yonrazticketing/tickets # us.gcr.io/myticketing-dev-420512/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
